    "use client";
    
    import { createContext, useContext, useState, useEffect, ReactNode } from "react";
    // Импортируем хуки для работы с роутингом Next.js
    import { usePathname, useRouter } from "next/navigation";
    
    type Lang = "ru" | "kg";
    
    interface LanguageContextType {
        lang: Lang;
        setLang: (lang: Lang) => void;
        t: (key: string) => string;
    }
    
    const LanguageContext = createContext<LanguageContextType | null>(null);
    
    const translations: Record<Lang, Record<string, string>> = {
        ru: {
            "nav.universities": "Университеты",
            "nav.countries": "Страны",
            "nav.programs": "Программы",
            "nav.online": "Онлайн-подготовка",
            "nav.about": "О нас",
            "nav.login": "Войти",
            "nav.consultation": "Получить консультацию",
            "hero.badge": "Лицензированный образовательный центр",
            "hero.title1": "поступи в",
            "hero.title2": "зарубежный",
            "hero.title3": "университет",
            "hero.desc": "Профессиональная подготовка и полное сопровождение для учеников 9–11 классов. От выбора университета до успешного поступления.",
            "hero.btn.consult": "Получить консультацию",
            "hero.btn.start": "Начать подготовку",
            "hero.stat1": "Поступивших студентов",
            "hero.stat2": "Университетов-партнёров",
            "hero.stat3": "Стран для обучения",
            "hero.manager": "Индивидуальный менеджер",
            "hero.manager.desc": "Персональное сопровождение 24/7",
            "exam.toefl.desc": "Подготовка к международным экзаменам в языковых клубах.",
            "exam.toefl.btn": "Получи план за 5 минут",
            "exam.toefl.sub": "Диагностика + план подготовки бесплатно",
            "exam.sat.desc": "Математика и English для поступления в США.",
            "exam.personal.desc": "Эссе, мотивационные письма и структура заявки.",
            "exam.gre.desc": "Подготовка к экзамену для поступления в аспирантуру.",
            "exam.gmat.desc": "Подготовка к тесту для бизнес-школ.",
            "exam.course": "Подобрать курс",
            "bento.title": "Почему GetGrant?",
            "bento.desc": "Мы предоставляем комплексную поддержку для успешного поступления в зарубежные университеты",
            "bento.1.title": "95% успеха",
            "bento.1.desc": "Наши студенты успешно поступают в топовые университеты мира",
            "bento.2.title": "Персональный менеджер",
            "bento.2.desc": "Индивидуальное сопровождение на всех этапах подготовки и поступления",
            "bento.3.title": "Лицензированный центр",
            "bento.3.desc": "Наши студенты успешно поступают в топовые университеты мира",
            "bento.4.title": "Поддержка 24/7",
            "bento.4.desc": "Всегда на связи для ответов на ваши вопросы",
            "bento.5.title": "15+ стран",
            "bento.5.desc": "Партнёрство с университетами мира",
            "bento.6.title": "Онлайн-подготовка",
            "bento.6.desc": "Курсы по языку, предметам и экзаменам",
            "section.programs": "Популярные программы",
            "section.programs.sub": "Выбирайте из топовых образовательных программ мира",
            "section.countries": "Популярные страны",
            "section.countries.sub": "Выбирайте страну для обучения из наших топовых направлений",
            "section.universities": "Университеты-партнёры",
            "section.universities.sub": "Мы работаем с ведущими университетами мира",
            // Убраны повторяющиеся "modal.title", перенесены в секцию auth
            "countries.title": "Выберите страну для обучения",
            "countries.subtitle": "Исследуйте образовательные возможности в ведущих странах мира",
            "countries.btn": "Подробнее о стране",
            "countries.notfound": "Страны не найдены",
            "country.advantages": "Преимущества обучения",
            "country.costs": "Стоимость жизни (в месяц)",
            "country.universities": "Топ университеты",
            "country.universities.all": "Показать все",
            "country.visas": "Визовая информация",
            "country.costs.category": "Категория",
            "country.costs.min": "Минимум",
            "country.costs.avg": "Среднее",
            "country.costs.max": "Максимум",
            "country.costs.total": "Итого",
            "universities.title": "Университеты",
            "universities.found": "Найдено",
            "universities.found2": "университетов",
            "universities.notfound": "Университеты не найдены. Попробуйте изменить фильтры.",
            "universities.showmore": "Показать еще",
            "universities.collapse": "Свернуть",
            "universities.shown": "Показано",
            "universities.of": "из",
            "filter.title": "Фильтр",
            "filter.search": "Поиск",
            "filter.search.placeholder": "Название университета",
            "filter.country": "Страна",
            "filter.type": "Тип университета",
            "filter.cost": "Стоимость обучения (в год)",
            "filter.reset": "Сбросить фильтр",
            "filter.private": "Частный",
            "filter.public": "Государственный",
            "uni.programs": "программ",
            "uni.students": "студентов",
            "uni.cost": "Стоимость",
            "uni.acceptance": "Процент поступления",
            "uni.type": "Тип",
            "uni.nophoto": "Нет изображения кампуса",
            "programs.title": "Программы",
            "programs.notfound": "Программы не найдены",
            "online.title": "Онлайн-подготовка",
            "online.subtitle": "Занятия с профессиональными преподавателями для успешного поступления",
            "about.title": "О нас",
            "programs.catalog": "Каталог программ",
            "programs.found": "Найдено",
            "programs.found2": "программ обучения",
            "programs.showmore": "Показать еще",
            "programs.collapse": "Свернуть",
            "programs.shown": "Показано",
            "programs.of": "из",
            "programs.filter.show": "Показать фильтры",
            "programs.filter.hide": "Скрыть фильтры",
            "about.label": "О нас",
            "about.hero.title1": "МЫ ПОМОГАЕМ МЕЧТАМ",
            "about.hero.title2": "СТАТЬ РЕАЛЬНОСТЬЮ",
            "about.hero.desc": "GetGrant — лицензированный образовательный центр из Бишкека. С 2018 года мы помогаем ученикам 9–11 классов поступить в лучшие университеты мира. Более 500 успешных историй.",
            "about.hero.btn": "Наши университеты",
            "about.mission.title": "Наша миссия",
            "about.mission.p1": "Мы верим, что качественное зарубежное образование доступно каждому способному студенту из Центральной Азии — нужно только знать как.",
            "about.mission.p2": "GetGrant убирает барьеры: языковой, информационный, бюрократический. Мы берём на себя всю сложность процесса — от выбора университета до получения визы — чтобы студент мог сосредоточиться на учёбе.",
            "about.mission.check1": "Персональный менеджер для каждого студента",
            "about.mission.check2": "Полное сопровождение от выбора до вылета",
            "about.mission.check3": "Прозрачный трекинг статуса поступления",
            "about.mission.check4": "Поддержка родителей на всех этапах",
            "about.values.title": "Наши ценности",
            "about.values.subtitle": "Принципы, которые лежат в основе всего что мы делаем",
            "about.values.1.title": "Результат",
            "about.values.1.desc": "Мы фокусируемся на реальном поступлении, а не просто на консультациях. Каждый студент получает персональный план.",
            "about.values.2.title": "Забота",
            "about.values.2.desc": "Понимаем, что поступление за рубеж — стресс для всей семьи. Поддерживаем на каждом шаге 24/7.",
            "about.values.3.title": "Эффективность",
            "about.values.3.desc": "Никакой воды — только конкретные шаги, дедлайны и чёткий план подготовки.",
            "about.values.4.title": "Честность",
            "about.values.4.desc": "Говорим правду о шансах поступления, стоимости и сложностях. Никаких пустых обещаний.",
            "about.history.title": "История GetGrant",
            "about.history.2018": "Основание GetGrant. Первые 5 студентов поступили в университеты Великобритании.",
            "about.history.2019": "Расширение до 50 студентов. Открытие направлений США и Канады.",
            "about.history.2020": "Переход в онлайн. Запуск курсов подготовки к IELTS и SAT.",
            "about.history.2021": "Партнёрство с 30+ университетами. 200 успешных поступлений.",
            "about.history.2022": "Получение лицензии на образовательную деятельность.",
            "about.history.2023": "Запуск платформы. 500+ студентов. Выход на рынок Казахстана.",
            "about.history.2024": "Запуск персонального сопровождения и трекинга поступления.",
            "about.licenses.title": "Лицензии и аккредитации",
            "about.licenses.subtitle": "Работаем официально и прозрачно",
            "about.licenses.cta.title": "Готовы начать обучение?",
            "about.licenses.cta.desc": "Получите персональную консультацию по выбору университета и помощь в подготовке документов",
            "about.licenses.cta.btn": "Получить консультацию",
            "about.stats.students": "Поступивших студентов",
            "about.stats.universities": "Университетов-партнёров",
            "about.stats.countries": "Стран для обучения",
            "about.stats.success": "Уровень успеха",
            "about.team.title": "Наша команда",
            "about.team.subtitle": "Эксперты с реальным опытом поступления в топовые университеты мира",
            "online.courses.title": "Популярные курсы",
            "online.courses.duration": "Длительность",
            "online.courses.lessons": "Занятий",
            "online.courses.students": "Студентов",
            "online.courses.price": "Стоимость",
            "online.courses.enroll": "Записаться",
            "online.teachers.title": "Наши преподаватели",
            "online.teachers.subtitle": "Профессиональные преподаватели для успешного поступления",
            "online.cta.title": "Готовы начать обучение?",
            "online.cta.desc": "Получите персональную консультацию по выбору университета и помощь в подготовке документов",
            "online.cta.btn": "Получить консультацию",
            "programs.filter.title": "Фильтр",
            "programs.filter.search": "Поиск",
            "programs.filter.search.placeholder": "Название программы",
            "programs.filter.direction": "Направление",
            "programs.filter.level": "Уровень",
            "programs.filter.reset": "Сбросить фильтр",
            "programs.grid.shown": "Показано",
            "programs.grid.of": "из",
            "programs.grid.label": "программ",
            "programs.grid.showmore": "Показать еще",
            "programs.grid.collapse": "Свернуть",
            "programs.grid.notfound": "Программы не найдены. Попробуйте изменить фильтры.",
    
            "auth.greeting": "Добро пожаловать!",
            "auth.greeting.desc": "Войдите в свой аккаунт, чтобы продолжить обучение и пользоваться всеми возможностями GetGrant.",
            "auth.greeting.desc.register": "Создайте аккаунт, чтобы начать подготовку и пользоваться всеми возможностями GetGrant.",
            "auth.label.email": "Email",
            "auth.label.password": "Пароль",
            "auth.forgot.link": "Забыли пароль?",
            "auth.reset.placeholder.password": "Введите пароль",
            "auth.placeholder.email": "email@example.com",
            "auth.btn.login": "Войти",
            "auth.btn.register": "Регистрация",
            "auth.or": "или",
            "auth.btn.google": "Войти через Google",
            "auth.btn.apple": "Войти через Apple",
            "auth.already.link": "Уже есть аккаунт?",
            "auth.noaccount.link": "Нет аккаунта?",
            "auth.register.link": "Регистрация",
            "auth.login.link": "Войти",
            "auth.promo.title": "Ваш путь к международному образованию",
            "auth.promo.subtitle": "Присоединяйтесь к тысячам студентов, которые уже строят своё будущее вместе с GetGrant.",
            "auth.promo.benefit1.title": "Подбор программ",
            "auth.promo.benefit1.desc": "Найдём лучшие программы и университеты под ваш профиль",
            "auth.promo.benefit2.title": "Поддержка на всех этапах",
            "auth.promo.benefit2.desc": "Сопровождаем от выбора до зачисления и адаптации",
            "auth.promo.benefit3.title": "Международные возможности",
            "auth.promo.benefit3.desc": "Обучение в ведущих университетах мира",
    
            "enroll.title": "Записаться на курс",
            "enroll.placeholder.group": "Выберите группу или время начала",
            "enroll.label.time": "Выберите удобное время",
            "enroll.label.format": "Формат обучения",
            "enroll.format.online": "Онлайн",
            "enroll.placeholder.date": "дд.мм.гггг",
            "enroll.placeholder.time": "--:--",
            "enroll.level.label": "Ваш уровень английского",
            "enroll.level.beginner": "Начальный (A1–A2)",
            "enroll.level.intermediate": "Средний (B1–B2)",
            "enroll.level.advanced": "Продвинутый (C1–C2)",
            "enroll.pricing.duration": "Длительность",
            "enroll.pricing.lessons": "Занятий",
            "enroll.pricing.price": "Стоимость курса",
            "enroll.pricing.discount": "Скидка",
            "enroll.pricing.total": "Итого к оплате",
            "enroll.legal.agree1": "Я согласен с условиями",
            "enroll.legal.agree2": "оферты",
            "enroll.legal.agree3": "и",
            "enroll.legal.agree4": "политикой возврата",
            "enroll.btn.cancel": "Отменить",
            "enroll.btn.payment": "Перейти к оплате",
    
            "booking.title": "ЗАПИСАТЬСЯ К ПРЕПОДАВАТЕЛЮ",
            "booking.teacher.specialization": "Специализация",
            "booking.teacher.experience": "Опыт работы",
            "booking.teacher.experience.years": "лет",
            "booking.teacher.experience.year": "год",
            "booking.teacher.experience.year_": "года",
            "booking.teacher.certificates": "Сертификаты",
            "booking.label.format": "Выберите формат занятия",
            "booking.type.individual": "Индивидуальное занятие",
            "booking.type.individual.desc": "Персональное занятие один на один с преподавателем",
            "booking.type.trial": "Пробное занятие (30 мин)",
            "booking.type.trial.desc": "Короткое знакомство и точная оценка текущего уровня",
            "booking.label.date": "Выберите дату и время",
            "booking.label.contacts": "Ваши контакты",
            "booking.placeholder.name": "Как к вам обращаться?",
            "booking.placeholder.email": "email@example.com",
            "booking.label.wishes": "Дополнительные пожелания (необязательно)",
            "booking.placeholder.wishes": "Расскажите о своих целях, уровне подготовки или особых пожеланиях...",
            "booking.legal.agree1": "Я согласен с условиями",
            "booking.legal.agree2": "оферты",
            "booking.legal.agree3": "и",
            "booking.legal.agree4": "политикой возврата",
            "booking.btn.cancel": "Отменить",
            "booking.btn.confirm": "Подтвердить запись",
            "modal.teacher.sub": "Записаться к преподавателю",
            "modal.teacher.format": "Выберите формат занятия",
            "modal.teacher.indiv.title": "Индивидуальное занятие",
            "modal.teacher.indiv.desc": "Персональное занятие один на один с преподавателем",
            "modal.teacher.trial.title": "Пробное занятие (30 мин)",
            "modal.teacher.trial.desc": "Короткое знакомство и точная оценка текущего уровня",
            "modal.teacher.datetime": "Выберите дату и время",
            "modal.teacher.contacts": "Ваши контакты",
            "modal.teacher.wishes": "Дополнительные пожелания",
            "modal.teacher.wishes.optional": "(необязательно)",
            "modal.teacher.wishes.placeholder": "Расскажите о своих целях, уровне подготовки или особых пожеланиях...",
            "modal.teacher.agree": "Я согласен с условиями",
            "modal.teacher.agree.terms": "оферты",
            "modal.teacher.agree.and": "и",
            "modal.teacher.agree.refund": "политикой возврата",
            "modal.teacher.submit": "Подтвердить запись",
    
            "modal.course.enroll": "Записаться на курс",
            "modal.course.duration": "Длительность",
            "modal.course.format": "Формат обучения",
            "modal.course.online": "Онлайн",
            "modal.course.time": "Выберите удобное время",
            "modal.course.time.placeholder": "Выберите группу или время начала",
            "modal.course.time.morning": "Утренняя группа (09:00 - 11:00)",
            "modal.course.time.day": "Дневная группа (14:00 - 16:00)",
            "modal.course.time.evening": "Вечерняя группа (19:00 - 21:00)",
            "modal.course.level": "Ваш уровень английского",
            "modal.course.level.a": "Начальный (A1–A2)",
            "modal.course.level.b": "Средний (B1–B2)",
            "modal.course.level.c": "Продвинутый (C1–C2)",
            "modal.course.price.base": "Стоимость курса",
            "modal.course.price.discount": "Скидка",
            "modal.course.price.total": "Итого к оплате",
            "modal.course.submit": "Перейти к оплате",
    
            "modal.consult.cancel": "Отменить",
            "modal.consult.title": "Получить консультацию",
            "modal.consult.name": "Имя",
            "modal.consult.name.placeholder": "Как к вам обращаться?",
            "modal.consult.email": "Email",
            "modal.consult.phone": "Телефон",
            "modal.consult.phone.optional": "опционально",
            "modal.consult.message": "Сообщение",
            "modal.consult.message.placeholder": "Например: интересуют страны, визы или пакет сопровождения...",
            "modal.consult.agree": "Я согласен на обработку",
            "modal.consult.agree.link": "персональных данных",
            "modal.consult.submit": "Отправить",
        },
    
        kg: {
            "nav.universities": "Университеттер",
            "nav.countries": "Өлкөлөр",
            "nav.programs": "Программалар",
            "nav.online": "Онлайн даярдык",
            "nav.about": "Биз жөнүндө",
            "nav.login": "Кирүү",
            "nav.consultation": "Консультация алуу",
            "hero.badge": "Лицензияланган билим берүү борбору",
            "hero.title1": "чет өлкөлүк",
            "hero.title2": "университетке",
            "hero.title3": "кир",
            "hero.desc": "9–11-класс окуучулары үчүн профессионалдык даярдык жана толук колдоо. Университетти тандоодон баштап ийгиликтүү кабыл алынганга чейин.",
            "hero.btn.consult": "Консультация алуу",
            "hero.btn.start": "Даярдыкты баштоо",
            "hero.stat1": "Кабыл алынган студенттер",
            "hero.stat2": "Өнөктөш университеттер",
            "hero.stat3": "Окуу үчүн өлкөлөр",
            "hero.manager": "Жеке менеджер",
            "hero.manager.desc": "Жеке колдоо 24/7",
            "exam.toefl.desc": "Тил клубдарында эл аралык экзаменге даярдык.",
            "exam.toefl.btn": "5 мүнөттө план алуу",
            "exam.toefl.sub": "Диагностика + даярдык планы бекер",
            "exam.sat.desc": "АКШга кабыл алуу үчүн математика жана англис тили.",
            "exam.personal.desc": "Эссе, мотивациялык каттар жана арыздын структурасы.",
            "exam.gre.desc": "Аспирантурага кабыл алуу үчүн экзаменге даярдык.",
            "exam.gmat.desc": "Бизнес-мектептер үчүн тестке даярдык.",
            "exam.course": "Курс тандоо",
            "bento.title": "Эмнеге GetGrant?",
            "bento.desc": "Биз чет өлкөлүк университеттерге ийгиликтүү кабыл алынуу үчүн комплекстүү колдоо көрсөтөбүз",
            "bento.1.title": "95% ийгилик",
            "bento.1.desc": "Биздин студенттер дүйнөнүн топ университеттерине ийгиликтүү кабыл алынат",
            "bento.2.title": "Жеке менеджер",
            "bento.2.desc": "Даярдоо жана кабыл алуунун бардык этаптарында жеке колдоо",
            "bento.3.title": "Лицензияланган борбор",
            "bento.3.desc": "Биздин студенттер дүйнөнүн топ университеттерине ийгиликтүү кабыл алынат",
            "bento.4.title": "Колдоо 24/7",
            "bento.4.desc": "Суроолоруңузга жооп берүүгө дайыма даярбыз",
            "bento.5.title": "15+ өлкө",
            "bento.5.desc": "Дүйнөнүн университеттери менен өнөктөштүк",
            "bento.6.title": "Онлайн даярдык",
            "bento.6.desc": "Тил, предметтер жана экзаменге курстар",
            "section.programs": "Популярдуу программалар",
            "section.programs.sub": "Дүйнөнүн топ билим берүү программаларынан тандаңыз",
            "section.countries": "Популярдуу өлкөлөр",
            "section.countries.sub": "Биздин топ багыттардан окуу өлкөсүн тандаңыз",
            "section.universities": "Өнөктөш университеттер",
            "section.universities.sub": "Биз дүйнөнүн жетектөөчү университеттери менен иштейбиз",
            // Убраны повторяющиеся "modal.title", перенесены в секцию auth
            "countries.title": "Окуу үчүн өлкө тандаңыз",
            "countries.subtitle": "Дүйнөнүн жетектөөчү өлкөлөрүндөгү билим берүү мүмкүнчүлүктөрүн изилдеңиз",
            "countries.btn": "Өлкө жөнүндө көбүрөөк",
            "countries.notfound": "Өлкөлөр табылган жок",
            "country.advantages": "Окуунун артыкчылыктары",
            "country.costs": "Жашоо куну (айына)",
            "country.universities": "Топ университеттер",
            "country.universities.all": "Баарын көрсөтүү",
            "country.visas": "Виза маалыматы",
            "country.costs.category": "Категория",
            "country.costs.min": "Минимум",
            "country.costs.avg": "Орточо",
            "country.costs.max": "Максимум",
            "country.costs.total": "Жыйынтык",
            "universities.title": "Университеттер",
            "universities.found": "Табылды",
            "universities.found2": "университет",
            "universities.notfound": "Университеттер табылган жок. Фильтрлерди өзгөртүп көрүңүз.",
            "universities.showmore": "Дагы көрсөтүү",
            "universities.collapse": "Жыйыштыруу",
            "universities.shown": "Көрсөтүлдү",
            "universities.of": "дан",
            "filter.title": "Фильтр",
            "filter.search": "Издөө",
            "filter.search.placeholder": "Университеттин аты",
            "filter.country": "Өлкө",
            "filter.type": "Университеттин түрү",
            "filter.cost": "Окуу баасы (жылына)",
            "filter.reset": "Фильтрди тазалоо",
            "filter.private": "Жеке",
            "filter.public": "Мамлекеттик",
            "uni.programs": "программа",
            "uni.students": "студент",
            "uni.cost": "Баасы",
            "uni.acceptance": "Кабыл алуу пайызы",
            "uni.type": "Түрү",
            "uni.nophoto": "Кампустун сүрөтү жок",
            "programs.title": "Программалар",
            "programs.notfound": "Программалар табылган жок",
            "online.title": "Онлайн даярдык",
            "online.subtitle": "Ийгиликтүү кабыл алынуу үчүн профессионал мугалимдер менен сабактар",
            "about.title": "Биз жөнүндө",
            "programs.catalog": "Программалар каталогу",
            "programs.found": "Табылды",
            "programs.found2": "окуу программасы",
            "programs.showmore": "Дагы көрсөтүү",
            "programs.collapse": "Жыйыштыруу",
            "programs.shown": "Көрсөтүлдү",
            "programs.of": "дан",
            "programs.filter.show": "Фильтрлерди көрсөтүү",
            "programs.filter.hide": "Фильтрлерди жашыруу",
            "about.label": "Биз жөнүндө",
            "about.hero.title1": "БИЗ КЫЯЛДАРДЫ",
            "about.hero.title2": "ЧЫНДЫККА АЙЛАНДЫРАБЫЗ",
            "about.hero.desc": "GetGrant — Бишкектеги лицензияланган билим берүү борбору. 2018-жылдан бери 9–11-класс окуучуларына дүйнөнүн эң жакшы университеттерине кабыл алынууга жардам берип келебиз. 500ден ашык ийгиликтүү окуя.",
            "about.hero.btn": "Биздин университеттер",
            "about.mission.title": "Биздин миссия",
            "about.mission.p1": "Борбордук Азиядагы ар бир жөндөмдүү студент үчүн сапаттуу чет өлкөлүк билим жеткиликтүү деп ишенебиз — жөн гана кантип экенин билүү керек.",
            "about.mission.p2": "GetGrant тоскообдуктарды жоюп берет: тилдик, маалыматтык, бюрократиялык. Университетти тандоодон виза алууга чейинки бардык татаалдыкты биз өз мойнубузга алабыз.",
            "about.mission.check1": "Ар бир студент үчүн жеке менеджер",
            "about.mission.check2": "Тандоодон учушка чейин толук колдоо",
            "about.mission.check3": "Кабыл алуу статусун ачык көзөмөлдөө",
            "about.mission.check4": "Бардык этаптарда ата-энелерди колдоо",
            "about.values.title": "Биздин баалуулуктар",
            "about.values.subtitle": "Биз жасаган нерселердин негизинде жаткан принциптер",
            "about.values.1.title": "Натыйжа",
            "about.values.1.desc": "Жөн гана консультациялар эмес, реалдуу кабыл алынууга багытталабыз. Ар бир студент жеке план алат.",
            "about.values.2.title": "Камкордук",
            "about.values.2.desc": "Чет өлкөгө кабыл алынуу бүтүндөй үй-бүлө үчүн стресс экенин түшүнөбүз. Ар бир кадамда 24/7 колдойбуз.",
            "about.values.3.title": "Натыйжалуулук",
            "about.values.3.desc": "Суу жок — конкреттүү кадамдар, мөөнөттөр жана так даярдык планы гана.",
            "about.values.4.title": "Чынчылдык",
            "about.values.4.desc": "Кабыл алынуу мүмкүнчүлүктөрү, баасы жана кыйынчылыктары жөнүндө чындыкты айтабыз.",
            "about.history.title": "GetGrant тарыхы",
            "about.history.2018": "GetGrant негизделди. Алгачкы 5 студент Улуу Британиянын университеттерине кабыл алынды.",
            "about.history.2019": "50 студентке чейин өсүү. АКШ жана Канада багыттары ачылды.",
            "about.history.2020": "Онлайнга өтүү. IELTS жана SAT даярдык курстары башталды.",
            "about.history.2021": "30+ университет менен өнөктөштүк. 200 ийгиликтүү кабыл алуу.",
            "about.history.2022": "Билим берүү ишмердигине лицензия алынды.",
            "about.history.2023": "Платформа ишке киргизилди. 500+ студент. Казакстан рыногуна чыгуу.",
            "about.history.2024": "Жеке колдоо жана кабыл алуу трекинги башталды.",
            "about.licenses.title": "Лицензиялар жана аккредитациялар",
            "about.licenses.subtitle": "Расмий жана ачык иштейбиз",
            "about.licenses.cta.title": "Окуону баштоого даярсызбы?",
            "about.licenses.cta.desc": "Университетти тандоо жана документтерди даярдоо боюнча жеке консультация алыңыз",
            "about.licenses.cta.btn": "Консультация алуу",
            "about.stats.students": "Кабыл алынган студенттер",
            "about.stats.universities": "Өнөктөш университеттер",
            "about.stats.countries": "Окуу үчүн өлкөлөр",
            "about.stats.success": "Ийгилик деңгээли",
            "about.team.title": "Биздин команда",
            "about.team.subtitle": "Дүйнөнүн топ университеттерине кабыл алынуунун реалдуу тажрыйбасы бар эксперттер",
            "online.courses.title": "Популярдуу курстар",
            "online.courses.duration": "Узактыгы",
            "online.courses.lessons": "Сабактар",
            "online.courses.students": "Студенттер",
            "online.courses.price": "Баасы",
            "online.courses.enroll": "Жазылуу",
            "online.teachers.title": "Биздин мугалимдер",
            "online.teachers.subtitle": "Ийгиликтүү кабыл алынуу үчүн профессионал мугалимдер",
            "online.cta.title": "Окуону баштоого даярсызбы?",
            "online.cta.desc": "Университетти тандоо жана документтерди даярдоо боюнча жеке консультация алыңыз",
            "online.cta.btn": "Консультация алуу",
            "programs.filter.title": "Фильтр",
            "programs.filter.search": "Издөө",
            "programs.filter.search.placeholder": "Программанын аты",
            "programs.filter.direction": "Багыт",
            "programs.filter.level": "Деңгээл",
            "programs.filter.reset": "Фильтрди тазалоо",
            "programs.grid.shown": "Көрсөтүлдү",
            "programs.grid.of": "дан",
            "programs.grid.label": "программа",
            "programs.grid.showmore": "Дагы көрсөтүү",
            "programs.grid.collapse": "Жыйыштыруу",
            "programs.grid.notfound": "Программалар табылган жок. Фильтрлерди өзгөртүп көрүңүз.",
            "auth.greeting": "Кош келиңиздер!",
            "auth.greeting.desc": "Окууну улантуу жана GetGrant'тын бардык мүмкүнчүлүктөрүн колдонуу үчүн аккаунтуңузга кириңиз.",
            "auth.greeting.desc.register": "Даярдыкты баштоо жана GetGrant'тын бардык мүмкүнчүлүктөрүн колдонуу үчүн аккаунт түзүңүз.",
            "auth.label.email": "Email",
            "auth.label.password": "Сырсөз",
            "auth.forgot.link": "Сырсөздү унутуп калдыңызбы?",
            "auth.reset.placeholder.password": "Сырсөздү киргизиңиз",
            "auth.placeholder.email": "email@example.com",
            "auth.btn.login": "Кирүү",
            "auth.btn.register": "Каттоо",
            "auth.or": "же",
            "auth.btn.google": "Google аркылуу кирүү",
            "auth.btn.apple": "Apple аркылуу кирүү",
            "auth.already.link": "Аккаунтуңуз барбы?",
            "auth.noaccount.link": "Аккаунт жокпу?",
            "auth.register.link": "Каттоо",
            "auth.login.link": "Кирүү",
            "auth.promo.title": "Эл аралык билим берүүгө болгон жолуңуз",
            "auth.promo.subtitle": "GetGrant менен бирге келечегин куруп жаткан миңдеген студенттерге кошулуңуз.",
            "auth.promo.benefit1.title": "Программаларды тандоо",
            "auth.promo.benefit1.desc": "Профилиңизге ылайыктуу эң жакшы программаларды жана университеттерди табабыз",
            "auth.promo.benefit2.title": "Бардык этаптарда колдоо",
            "auth.promo.benefit2.desc": "Тандоодон баштап кабыл алууга жана адаптацияга чейин коштойбуз",
            "auth.promo.benefit3.title": "Эл аралык мүмкүнчүлүктөр",
            "auth.promo.benefit3.desc": "Дүйнөнүн жетектөөчү университеттеринде окуу",
            "enroll.title": "Курска жазылуу",
            "enroll.placeholder.group": "Топту же башталган убакты тандаңыз",
            "enroll.label.time": "Ыңгайлуу убакты тандаңыз",
            "enroll.label.format": "Окуу форматы",
            "enroll.format.online": "Онлайн",
            "enroll.placeholder.date": "кк.мм.жжжж",
            "enroll.placeholder.time": "--:--",
            "enroll.level.label": "Англис тилиңиздин деңгээли",
            "enroll.level.beginner": "Башталгыч (A1–A2)",
            "enroll.level.intermediate": "Орточо (B1–B2)",
            "enroll.level.advanced": "Жогорку (C1–C2)",
            "enroll.pricing.duration": "Узактыгы",
            "enroll.pricing.lessons": "Сабактар",
            "enroll.pricing.price": "Курстун баасы",
            "enroll.pricing.discount": "Арзандатуу",
            "enroll.pricing.total": "Төлөмдүн жыйынтыгы",
            "enroll.legal.agree1": "Мен шарттарга макулмун",
            "enroll.legal.agree2": "офертанын",
            "enroll.legal.agree3": "жана",
            "enroll.legal.agree4": "кайтаруу саясатынын",
            "enroll.btn.cancel": "Жокко чыгаруу",
            "enroll.btn.payment": "Төлөмгө өтүү",
            "booking.title": "МУГАЛИМГЕ ЖАЗЫЛУУ",
            "booking.teacher.specialization": "Адистиги",
            "booking.teacher.experience": "Иш тажрыйбасы",
            "booking.teacher.experience.years": "жыл",
            "booking.teacher.experience.year": "жыл",
            "booking.teacher.experience.year_": "жыл",
            "booking.teacher.certificates": "Сертификаттар",
            "booking.label.format": "Сабактын форматын тандаңыз",
            "booking.type.individual": "Жеке сабак",
            "booking.type.individual.desc": "Мугалим менен бирме-бир жеке сабак",
            "booking.type.trial": "Сыноо сабагы (30 мүн)",
            "booking.type.trial.desc": "Кыскача таанышуу жана учурдагы деңгээлди так баалоо",
            "booking.label.date": "Күндү жана убакты тандаңыз",
            "booking.label.contacts": "Сиздин контакттарыңыз",
            "booking.placeholder.name": "Сизге кантип кайрылуу керек?",
            "booking.placeholder.email": "email@example.com",
            "booking.label.wishes": "Кошумча каалоолор (милдеттүү эмес)",
            "booking.placeholder.wishes": "Максаттарыңыз, даярдык деңгээлиңиз же өзгөчө каалоолоруңуз жөнүндө айтып бериңиз...",
            "booking.legal.agree1": "Мен шарттарга макулмун",
            "booking.legal.agree2": "офертанын",
            "booking.legal.agree3": "жана",
            "booking.legal.agree4": "кайтаруу саясатынын",
            "booking.btn.cancel": "Жокко чыгаруу",
            "booking.btn.confirm": "Жазылууну ырастоо",
            "modal.consult.title": "Консультация алуу",
            "modal.consult.name": "Атыңыз",
            "modal.consult.name.placeholder": "Сизге кантип кайрылса болот?",
            "modal.consult.email": "Email",
            "modal.consult.phone": "Телефон",
            "modal.consult.phone.optional": "милдеттүү эмес",
            "modal.consult.message": "Билдирүү",
            "modal.consult.message.placeholder": "Мисалы: өлкөлөр, визалар же коштоо пакеттери кызыктырат...",
            "modal.consult.agree": "Мен иштетүүгө макулмун",
            "modal.consult.agree.link": "жеке маалыматтарды",
            "modal.consult.cancel": "Жокко чыгаруу",
            "modal.consult.submit": "Жөнөтүү",
            "modal.course.enroll": "Курска жазылуу",
            "modal.course.duration": "Узактыгы",
            "modal.course.format": "Окуу форматы",
            "modal.course.online": "Онлайн",
            "modal.course.time": "Ыңгайлуу убакты тандаңыз",
            "modal.course.time.placeholder": "Топту же башталган убакты тандаңыз",
            "modal.course.time.morning": "Утренний топ (09:00 - 11:00)",
            "modal.course.time.day": "Дневной топ (14:00 - 16:00)",
            "modal.course.time.evening": "Вечерний топ (19:00 - 21:00)",
            "modal.course.level": "Англис тилиңиздин деңгээли",
            "modal.course.level.a": "Башталгыч (A1–A2)",
            "modal.course.level.b": "Орточо (B1–B2)",
            "modal.course.level.c": "Жогорку (C1–C2)",
            "modal.course.price.base": "Курстун баасы",
            "modal.course.price.discount": "Арзандатуу",
            "modal.course.price.total": "Төлөмдүн жыйынтыгы",
            "modal.course.submit": "Төлөмгө өтүү",
            "modal.teacher.sub": "Мугалим",
            "modal.teacher.format": "Сабактын форматын тандаңыз",
            "modal.teacher.indiv.title": "Жекече сабак",
            "modal.teacher.indiv.desc": "Мугалим менен бирме-бир жекече сабак өтүү",
            "modal.teacher.trial.title": "Сыноо сабагы (30 мүн)",
            "modal.teacher.trial.desc": "Кыскача таанышуу жана учурдагы деңгээлди так баалоо",
            "modal.teacher.datetime": "Күндү жана убакты тандаңыз",
            "modal.teacher.contacts": "Сиздин байланыштарыңыз",
            "modal.teacher.wishes": "Кошумча каалоолор",
            "modal.teacher.wishes.optional": "(милдеттүү эмес)",
            "modal.teacher.wishes.placeholder": "Максаттарыңыз, даярдык деңгээлиңиз же өзгөчө каалоолоруңуз жөнүндө айтып бериңиз...",
            "modal.teacher.submit": "Жазууну ырастоо",
        },
    };
    
    export function LanguageProvider({
                                         children,
                                         initialLang = "ru",
                                     }: {
        children: ReactNode;
        initialLang?: Lang;
    }) {
        const [lang, setLangState] = useState<Lang>(initialLang);
    
        const router = useRouter();
        const pathname = usePathname();
    
        useEffect(() => {
            const cookieLang = document.cookie
                .split("; ")
                .find((row) => row.startsWith("lang="))
                ?.split("=")[1] as Lang | undefined;
    
            if (cookieLang === "ru" || cookieLang === "kg") {
                setLangState(cookieLang);
            }
        }, []);

        const setLang = (newLang: Lang) => {
            setLangState(newLang);
            document.cookie = `lang=${newLang};path=/;max-age=31536000;SameSite=Lax`;

            if (pathname) {
                const segments = pathname.split("/");
                segments[1] = newLang;
                const newPath = segments.join("/");
                router.replace(newPath);
            }
        };
    
        const t = (key: string): string => {
            return translations[lang][key] ?? translations["ru"][key] ?? key;
        };
    
        return (
            <LanguageContext.Provider value={{ lang, setLang, t }}>
                {children}
            </LanguageContext.Provider>
        );
    }
    
    export function useLanguage() {
        const ctx = useContext(LanguageContext);
        if (!ctx) {
            return {
                lang: "ru" as Lang,
                setLang: (_lang: Lang) => {},
                t: (key: string): string => translations["ru"][key] ?? key,
            };
        }
        return ctx;
    }